"""Relationship

Revision ID: 9d4fd1199cd3
Revises: d00431b6c9b9
Create Date: 2023-09-17 12:56:01.450308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d4fd1199cd3'
down_revision = 'd00431b6c9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blogger_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['blogger_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('blogger_id')

    # ### end Alembic commands ###
