"""Comment Author

Revision ID: dd95224c453b
Revises: 0cb4b188b7c8
Create Date: 2023-10-22 14:58:05.272149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd95224c453b'
down_revision = '0cb4b188b7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blogger_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['blogger_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('blogger_id')

    # ### end Alembic commands ###
